"""added user blocking model

Revision ID: 1753c3aa0f11
Revises: e4c13932e4da
Create Date: 2022-05-15 06:18:47.751189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1753c3aa0f11'
down_revision = 'e4c13932e4da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_block',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['user.id'], name=op.f('fk_user_block_target_id_user')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_block_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', 'target_id', name=op.f('pk_user_block'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_block')
    # ### end Alembic commands ###
