"""initial

Revision ID: 28c36ec6d4f1
Revises: a01385879f1b
Create Date: 2022-05-13 19:18:32.666549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28c36ec6d4f1'
down_revision = 'a01385879f1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user_access_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=True))
        batch_op.drop_column('reated')

    with op.batch_alter_table('user_follower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated', sa.DateTime(), nullable=True))
        batch_op.drop_column('reated')

    with op.batch_alter_table('user_privilege', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated', sa.DateTime(), nullable=True))
        batch_op.drop_column('reated')

    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated', sa.DateTime(), nullable=True))
        batch_op.drop_column('reated')

    with op.batch_alter_table('user_social_link_other', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated', sa.DateTime(), nullable=True))
        batch_op.drop_column('reated')

    with op.batch_alter_table('user_social_links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated', sa.DateTime(), nullable=True))
        batch_op.drop_column('reated')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_social_links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reated', sa.DATETIME(), nullable=True))
        batch_op.drop_column('updated')
        batch_op.drop_column('created')

    with op.batch_alter_table('user_social_link_other', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reated', sa.DATETIME(), nullable=True))
        batch_op.drop_column('updated')
        batch_op.drop_column('created')

    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reated', sa.DATETIME(), nullable=True))
        batch_op.drop_column('updated')
        batch_op.drop_column('created')

    with op.batch_alter_table('user_privilege', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reated', sa.DATETIME(), nullable=True))
        batch_op.drop_column('updated')
        batch_op.drop_column('created')

    with op.batch_alter_table('user_follower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reated', sa.DATETIME(), nullable=True))
        batch_op.drop_column('updated')
        batch_op.drop_column('created')

    with op.batch_alter_table('user_access_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reated', sa.DATETIME(), nullable=True))
        batch_op.drop_column('created')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('updated')
        batch_op.drop_column('created')

    # ### end Alembic commands ###
