"""initial

Revision ID: bcc94594d15d
Revises: 2247a78bbda9
Create Date: 2022-05-13 21:37:21.782240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcc94594d15d'
down_revision = '2247a78bbda9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_follower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_user_follower_follower_id_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_follower_target_id_user'), 'user', ['target_id'], ['id'])
        batch_op.drop_column('follower_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_follower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('follower_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_user_follower_target_id_user'), type_='foreignkey')
        batch_op.create_foreign_key('fk_user_follower_follower_id_user', 'user', ['follower_id'], ['id'])
        batch_op.drop_column('target_id')

    # ### end Alembic commands ###
