"""initial

Revision ID: e4c13932e4da
Revises: bcc94594d15d
Create Date: 2022-05-13 23:04:33.712054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4c13932e4da'
down_revision = 'bcc94594d15d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_access_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_access_token',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('token', sa.VARCHAR(length=256), nullable=True),
    sa.Column('expires', sa.DATETIME(), nullable=True),
    sa.Column('created', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_user_access_token_user_id_user'),
    sa.PrimaryKeyConstraint('user_id', name='pk_user_access_token')
    )
    # ### end Alembic commands ###
