"""renamed UserFollowing to UserFollow

Revision ID: f5d4f28b812e
Revises: 1753c3aa0f11
Create Date: 2022-05-16 00:45:49.110278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5d4f28b812e'
down_revision = '1753c3aa0f11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_follow',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['user.id'], name=op.f('fk_user_follow_target_id_user')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_follow_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', 'target_id', name=op.f('pk_user_follow'))
    )
    op.drop_table('user_follower')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_follower',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('target_id', sa.INTEGER(), nullable=False),
    sa.Column('created', sa.DATETIME(), nullable=True),
    sa.Column('updated', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['user.id'], name='fk_user_follower_target_id_user'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_user_follower_user_id_user'),
    sa.PrimaryKeyConstraint('user_id', name='pk_user_follower')
    )
    op.drop_table('user_follow')
    # ### end Alembic commands ###
